"""Portability routes — export and import memory bundles (PORT-01).

Bundle format v2 (GPT5.6 #8/#17 — the bundle now carries the state that cannot be
recomputed from raw content: user-curated canonical memory and the deletion ledger):
{
  "format": "recalium-memory-bundle",
  "version": "2",
  "exported_at": "<ISO 8601>",
  "items": [ { raw archive item — see below } ],
  "canonical_memory": [ { user-promoted canonical item with provenance_note } ],
  "tombstones": [ { deletion-ledger entry: source_id, content_hash, ... } ]
}

Each raw item: id, source_type, source_name, ingested_at, raw_content, content_hash,
conversation_count, metadata.

Deleted items are excluded from ``items`` (PRIV-03), but their tombstones ARE exported
so a receiving instance will not resurrect deleted content on import. Derived state
(summaries, facts, embeddings, links) is regenerated by the pipeline when raw items are
re-ingested, so it is intentionally not duplicated in the bundle.

v1 bundles (items only) are still accepted on import.
"""
from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import JSONResponse
from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncSession

from app.domain.archive.models import RawArchiveItem, Tombstone
from app.domain.archive.tombstones import DEFAULT_BACKUP_DIR, append_tombstone_ledger
from app.domain.canonical_memory.models import CanonicalMemoryItem
from app.domain.ingest.service import ingest_text_content
from app.infrastructure.db import get_session

logger = logging.getLogger(__name__)
router = APIRouter()

_BUNDLE_FORMAT = "recalium-memory-bundle"
_BUNDLE_VERSION = "2"
_SUPPORTED_IMPORT_VERSIONS = frozenset({"1", "2"})


@router.get("/export/bundle")
async def export_bundle(session: AsyncSession = Depends(get_session)) -> JSONResponse:
    """GET /api/export/bundle — export non-deleted raw items, canonical memory, and the
    deletion ledger as a portable JSON bundle (GPT5.6 #8/#17)."""
    result = await session.execute(
        select(RawArchiveItem)
        .where(RawArchiveItem.deleted_at.is_(None))
        .order_by(RawArchiveItem.ingested_at)
    )
    items = result.scalars().all()

    canonical = (
        await session.execute(
            select(CanonicalMemoryItem)
            .where(CanonicalMemoryItem.source_status == "active")
            .order_by(CanonicalMemoryItem.created_at)
        )
    ).scalars().all()

    tombstones = (
        await session.execute(select(Tombstone).order_by(Tombstone.removed_at))
    ).scalars().all()

    bundle = {
        "format": _BUNDLE_FORMAT,
        "version": _BUNDLE_VERSION,
        "exported_at": datetime.now(timezone.utc).isoformat(),
        "items": [
            {
                "id": str(item.id),
                "source_type": item.source_type,
                "source_name": item.source_name,
                "ingested_at": item.ingested_at.isoformat(),
                "raw_content": item.raw_content,
                "content_hash": item.content_hash,
                "conversation_count": item.conversation_count,
                "metadata": item.metadata_json,
            }
            for item in items
        ],
        "canonical_memory": [
            {
                "id": str(c.id),
                "content": c.content,
                "status": c.status,
                "promoted_from": c.promoted_from,
                "promoted_by": c.promoted_by,
                "provenance_note": c.provenance_note,
                "raw_archive_id": str(c.raw_archive_id) if c.raw_archive_id else None,
                "fact_id": str(c.fact_id) if c.fact_id else None,
                "created_at": c.created_at.isoformat() if c.created_at else None,
            }
            for c in canonical
        ],
        "tombstones": [
            {
                "source_id": str(t.source_id),
                "content_hash": t.content_hash,
                "removal_type": t.removal_type,
                "removed_at": t.removed_at.isoformat() if t.removed_at else None,
                "actor": t.actor,
                "reason": t.reason,
            }
            for t in tombstones
        ],
    }

    return JSONResponse(
        content=bundle,
        headers={"Content-Disposition": 'attachment; filename="recalium-bundle.json"'},
    )


@router.post("/import/bundle")
async def import_bundle(
    bundle: dict,
    session: AsyncSession = Depends(get_session),
) -> dict:
    """POST /api/import/bundle — import a memory bundle JSON (v1 or v2).

    GPT5.6 #8/#17: applies the bundle's tombstones first so deleted content is never
    resurrected on import, then imports raw items (skipping tombstoned/duplicate
    content) and user-curated canonical memory.
    """
    if bundle.get("format") != _BUNDLE_FORMAT:
        raise HTTPException(
            status_code=422,
            detail=f"Invalid bundle format: expected '{_BUNDLE_FORMAT}', "
                   f"got '{bundle.get('format')}'",
        )
    if str(bundle.get("version", "")) not in _SUPPORTED_IMPORT_VERSIONS:
        raise HTTPException(
            status_code=422,
            detail=f"Unsupported bundle version: expected one of "
                   f"{sorted(_SUPPORTED_IMPORT_VERSIONS)}, got '{bundle.get('version')}'",
        )

    items = bundle.get("items", [])
    if not isinstance(items, list):
        raise HTTPException(status_code=422, detail="Bundle 'items' must be a list")

    # ── Apply tombstones first (GPT5.6 #8): a receiving instance must honor
    # deletions recorded elsewhere and must not import content that was deleted.
    tombstoned_hashes: set[str] = set()
    tombstones_applied = await _apply_bundle_tombstones(
        session, bundle.get("tombstones", []), tombstoned_hashes
    )

    imported = 0
    skipped = 0
    errors: list[str] = []

    for i, item in enumerate(items):
        content_hash = item.get("content_hash", "")
        raw_content = item.get("raw_content", "")
        source_name = item.get("source_name")

        if not raw_content:
            errors.append(f"Item {i}: missing raw_content")
            continue

        # Never resurrect content the bundle marks as deleted.
        if content_hash and content_hash in tombstoned_hashes:
            skipped += 1
            continue

        # Dedup check: skip if content_hash already exists (including deleted).
        if content_hash:
            existing = await session.execute(
                text("SELECT id FROM raw_archive WHERE content_hash = :hash"),
                {"hash": content_hash},
            )
            if existing.fetchone() is not None:
                skipped += 1
                continue

        try:
            await ingest_text_content(
                session=session,
                content=raw_content,
                source_name=source_name,
            )
            await session.flush()
            imported += 1
        except Exception as exc:
            await session.rollback()
            errors.append(f"Item {i} ({source_name!r}): {exc}")

    canonical_imported = await _import_canonical(
        session, bundle.get("canonical_memory", []), errors
    )

    await session.commit()

    logger.info(
        "Bundle import complete: imported=%d skipped=%d canonical=%d tombstones=%d errors=%d",
        imported, skipped, canonical_imported, tombstones_applied, len(errors),
    )
    return {
        "imported": imported,
        "skipped": skipped,
        "canonical_imported": canonical_imported,
        "tombstones_applied": tombstones_applied,
        "errors": errors,
    }


async def _apply_bundle_tombstones(
    session: AsyncSession,
    tombstones: list,
    tombstoned_hashes: set[str],
) -> int:
    """Import the bundle's deletion ledger (GPT5.6 #8).

    For each tombstone: record its content_hash (so matching raw items are not
    imported), create a durable Tombstone row if absent, mirror it to the external
    ledger, and suppress any existing local content with the same hash so a prior
    import cannot survive a deletion recorded elsewhere.
    """
    if not isinstance(tombstones, list):
        return 0
    applied = 0
    for t in tombstones:
        content_hash = (t or {}).get("content_hash")
        if not content_hash:
            continue
        tombstoned_hashes.add(content_hash)

        exists = (
            await session.execute(
                select(Tombstone.id).where(Tombstone.content_hash == content_hash).limit(1)
            )
        ).first()
        if exists is None:
            source_id_raw = t.get("source_id")
            try:
                source_id = uuid.UUID(str(source_id_raw)) if source_id_raw else uuid.uuid4()
            except (ValueError, TypeError):
                source_id = uuid.uuid4()
            session.add(
                Tombstone(
                    source_id=source_id,
                    content_hash=content_hash,
                    removal_type=str(t.get("removal_type") or "delete")[:16],
                    removed_at=datetime.now(timezone.utc),
                    actor=str(t.get("actor") or "bundle_import")[:128],
                    reason=t.get("reason") or "imported from memory bundle",
                )
            )
            append_tombstone_ledger(
                {
                    "source_id": str(source_id),
                    "content_hash": content_hash,
                    "removal_type": str(t.get("removal_type") or "delete"),
                    "removed_at": datetime.now(timezone.utc).isoformat(),
                    "actor": str(t.get("actor") or "bundle_import"),
                    "reason": t.get("reason") or "imported from memory bundle",
                },
                DEFAULT_BACKUP_DIR,
            )
            applied += 1

        # Suppress any already-present local content matching this deletion.
        await session.execute(
            text(
                "UPDATE raw_archive SET deleted_at = COALESCE(deleted_at, :now) "
                "WHERE content_hash = :hash"
            ),
            {"now": datetime.now(timezone.utc), "hash": content_hash},
        )
    return applied


async def _import_canonical(
    session: AsyncSession,
    canonical: list,
    errors: list[str],
) -> int:
    """Import user-curated canonical memory (GPT5.6 #8/#17).

    Canonical content and its provenance_note are preserved. Source ids (raw_archive_id,
    fact_id) are not carried across instances, so they are left null; the provenance_note
    retains the original source_content_hash/source_span for the derivation record.
    Deduped by identical active content.
    """
    if not isinstance(canonical, list):
        return 0
    count = 0
    for i, c in enumerate(canonical):
        content = (c or {}).get("content")
        if not content:
            continue
        existing = (
            await session.execute(
                select(CanonicalMemoryItem.id).where(
                    CanonicalMemoryItem.content == content,
                    CanonicalMemoryItem.source_status == "active",
                ).limit(1)
            )
        ).first()
        if existing is not None:
            continue
        try:
            session.add(
                CanonicalMemoryItem(
                    id=uuid.uuid4(),
                    content=content,
                    status=str(c.get("status") or "active"),
                    source_status="active",
                    promoted_from=str(c.get("promoted_from") or "manual"),
                    promoted_by=str(c.get("promoted_by") or "bundle_import"),
                    provenance_note=c.get("provenance_note"),
                )
            )
            await session.flush()
            count += 1
        except Exception as exc:  # noqa: BLE001
            await session.rollback()
            errors.append(f"Canonical {i}: {exc}")
    return count
